import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";
import "@repo/shadcn/globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main className="bg-brand relative min-h-[4000px] w-full">
          {/* order should be maintained - first navbar then sidebar; padding 80px is same as sidebar width  */}
          <div className="bg-brand fixed inset-0 h-[70px] w-full pl-[80px]">
            <Navbar />
          </div>

          {/* width is 10px more than navbar height */}
          <div className="bg-brand fixed inset-0 h-full max-w-[80px]">
            <Sidebar />
          </div>

          {/* padding-top same as navbar height; padding-left same as sidebar width */}
          <div className="pl-[80px] pt-[70px] text-white">{children}</div>
        </main>
      </body>
    </html>
  );
}
